# Generated by Django 5.0.7 on 2024-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
