# Generated by Django 5.0.7 on 2024-08-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projects_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
