# Generated by Django 5.0.7 on 2024-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projects_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screenshot',
            field=models.URLField(),
        ),
    ]
